/* SPDX-License-Identifier: LGPL-3.0-or-later
 *
 * AUTO-GENERATED by tools/derive-magic.py 64 62.
 * DO NOT HAND-EDIT. Re-run the deriver and commit the new output if
 * the divisor or bit width changes.
 *
 * Granlund-Moeller magic constant for unsigned divide-by-62 via
 * the high N bits of an N x N -> 2N multiply.
 *
 * For every value < 2^64 the reciprocal computation
 *
 *     q' = (value * KSUID_DIV62_M) >> 64
 *     r' = value - q' * 62
 *     if (r' >= 62) { ++q'; r' -= 62; }
 *
 * yields the same q', r' as the straight integer division
 * value / 62, value % 62. mulhi(value, M) may
 * underestimate the true quotient by exactly 1 for some inputs and
 * the correction step recovers it; mulhi never overestimates,
 * which is why M is the FLOOR of 2^N / d (not the ceiling -- the
 * ceiling form would overestimate for some inputs and the standard
 * correction would not catch it).
 *
 * Property pinned at compile time in the consuming TU:
 *     2^64 - M * 62 = 16   (must satisfy 0 <= ... <= d - 1)
 *
 * This file is regenerated by `tools/derive-magic.py` and verified
 * by `tests/test_divisor_magic.c` on every CI run.
 */
#ifndef KSUID_DIVISOR_MAGIC_H
#define KSUID_DIVISOR_MAGIC_H

#include <stdint.h>

#define KSUID_DIV62_M_BITS 64
#define KSUID_DIV62_M ((uint64_t) UINT64_C (0x421084210842108))
#define KSUID_DIV62_M_2N_MINUS_M_TIMES_D 16

#endif /* KSUID_DIVISOR_MAGIC_H */
