#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Granlund-Moeller magic-constant deriver. Generates the M constant
# such that for every value < 2^N, value / d == (value * M) >> N
# (with at most one off-by-one correction step using value - q*d >= d).
#
# Usage:
#   tools/derive-magic.py <N> <d> [<output-header>]
#
# Example:
#   tools/derive-magic.py 64 62 libksuid/divisor_magic.h
#
# This script exists because every architect/critic in the issue-#13
# review chain hand-derived a different (and wrong) constant for the
# divide-by-62 reciprocal. Sourcing the magic from a verified
# programmatic generator, with the resulting header committed to the
# tree alongside its generation arguments and a _Static_assert in
# the consuming TU, removes that class of error.
#
# Mathematical contract for M = floor(2^N / d):
#   - M * d <= 2^N (definition of floor)
#   - M * d >= 2^N - (d - 1) (because floor of integer division by
#     d differs from ceiling by at most 1, scaled by d)
# These together imply 0 <= 2^N - M * d <= d - 1, which is the
# precondition under which mulhi(v, M) >= v/d - 1 (mulhi may
# underestimate by exactly 1, never overestimates) and the
# standard Granlund-Moeller correction step
#     r = v - q * d; if (r >= d) { ++q; r -= d; }
# recovers the exact quotient + remainder.
#
# Note: ceiling(2^N / d) does NOT satisfy this contract -- with
# ceiling, mulhi(v, M) can OVERESTIMATE for large v and the
# correction's "if (r >= d)" check fires when it shouldn't,
# producing an off-by-one quotient. The earlier issue-#13
# discussion landed on the wrong constant precisely because
# multiple reviewers conflated ceiling vs floor; see the issue
# comment for the failure mode.

import sys


def derive_magic(n_bits: int, divisor: int) -> int:
    if not (1 < divisor < (1 << n_bits)):
        raise ValueError(f"divisor must satisfy 1 < d < 2^{n_bits}; got {divisor}")
    two_n = 1 << n_bits
    # floor(2^N / d): M * d is at most 2^N, the standard
    # Granlund-Moeller "underestimate" form that pairs with the
    # post-multiply remainder-based correction step.
    m = two_n // divisor
    # Sanity: 2^N - M * d is in [0, d - 1] (i.e. 2^N mod d).
    deficit = two_n - m * divisor
    if not (0 <= deficit <= divisor - 1):
        raise AssertionError(
            f"derived M={m:#x} fails precondition: 2^N - M*d = {deficit} "
            f"not in [0, {divisor - 1}]"
        )
    return m


def verify_against_reference(n_bits: int, divisor: int, m: int, samples: int) -> None:
    """Cross-check the magic constant by running the Granlund-Moeller scalar
    reciprocal across `samples` random values and asserting it equals
    the straight integer division. Fails loudly if M is wrong."""
    import random
    rng = random.Random(0x9E3779B97F4A7C15)
    mask = (1 << n_bits) - 1
    for _ in range(samples):
        v = rng.randint(0, mask)
        q_ref = v // divisor
        # mulhi: high N bits of v * M
        q_mul = (v * m) >> n_bits
        r = v - q_mul * divisor
        if r >= divisor:
            q_mul += 1
            r -= divisor
        if q_mul != q_ref:
            raise AssertionError(
                f"magic constant verification failed at v={v:#x}: "
                f"reference quotient {q_ref}, magic {q_mul}"
            )


def emit_header(path: str, n_bits: int, divisor: int, m: int) -> None:
    deficit = (1 << n_bits) - m * divisor
    text = f"""/* SPDX-License-Identifier: LGPL-3.0-or-later
 *
 * AUTO-GENERATED by tools/derive-magic.py {n_bits} {divisor}.
 * DO NOT HAND-EDIT. Re-run the deriver and commit the new output if
 * the divisor or bit width changes.
 *
 * Granlund-Moeller magic constant for unsigned divide-by-{divisor} via
 * the high N bits of an N x N -> 2N multiply.
 *
 * For every value < 2^{n_bits} the reciprocal computation
 *
 *     q' = (value * KSUID_DIV{divisor}_M) >> {n_bits}
 *     r' = value - q' * {divisor}
 *     if (r' >= {divisor}) {{ ++q'; r' -= {divisor}; }}
 *
 * yields the same q', r' as the straight integer division
 * value / {divisor}, value % {divisor}. mulhi(value, M) may
 * underestimate the true quotient by exactly 1 for some inputs and
 * the correction step recovers it; mulhi never overestimates,
 * which is why M is the FLOOR of 2^N / d (not the ceiling -- the
 * ceiling form would overestimate for some inputs and the standard
 * correction would not catch it).
 *
 * Property pinned at compile time in the consuming TU:
 *     2^{n_bits} - M * {divisor} = {deficit}   (must satisfy 0 <= ... <= d - 1)
 *
 * This file is regenerated by `tools/derive-magic.py` and verified
 * by `tests/test_divisor_magic.c` on every CI run.
 */
#ifndef KSUID_DIVISOR_MAGIC_H
#define KSUID_DIVISOR_MAGIC_H

#include <stdint.h>

#define KSUID_DIV{divisor}_M_BITS {n_bits}
#define KSUID_DIV{divisor}_M ((uint{n_bits}_t) UINT{n_bits}_C ({m:#x}))
#define KSUID_DIV{divisor}_M_2N_MINUS_M_TIMES_D {deficit}

#endif /* KSUID_DIVISOR_MAGIC_H */
"""
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def main(argv: list[str]) -> int:
    if not (3 <= len(argv) <= 4):
        sys.stderr.write(
            "usage: derive-magic.py <N-bits> <divisor> [<output-header>]\n"
        )
        return 2
    n_bits = int(argv[1])
    divisor = int(argv[2])
    out_path = argv[3] if len(argv) == 4 else None

    m = derive_magic(n_bits, divisor)
    verify_against_reference(n_bits, divisor, m, samples=1 << 16)

    if out_path is None:
        deficit = (1 << n_bits) - m * divisor
        print(f"M = {m:#x}  (2^{n_bits} - M * {divisor} = {deficit})")
        return 0

    emit_header(out_path, n_bits, divisor, m)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
